// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfSaAcRwiX96rOEldNII-m8YveyrzcyZw',
    appId: '1:171363030253:web:dd805f6154db29c916e8e4',
    messagingSenderId: '171363030253',
    projectId: 'syncpass-157f7',
    authDomain: 'syncpass-157f7.firebaseapp.com',
    storageBucket: 'syncpass-157f7.firebasestorage.app',
    measurementId: 'G-VN1ZPNSBEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMykGh0KuDFkJEDAASExKhwPkyYzakBeI',
    appId: '1:171363030253:android:4febb1e01753045916e8e4',
    messagingSenderId: '171363030253',
    projectId: 'syncpass-157f7',
    storageBucket: 'syncpass-157f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO9JQDT11Bvy5jTs0hffjxl6GAcBARGZo',
    appId: '1:171363030253:ios:c3a2e7c3dd33638e16e8e4',
    messagingSenderId: '171363030253',
    projectId: 'syncpass-157f7',
    storageBucket: 'syncpass-157f7.firebasestorage.app',
    iosBundleId: 'com.example.syncPass',
  );

}